# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - publish-meow-ui-vite
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: ^7.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd ./packages/meow-ui-vite && pnpm install
      - run: cd ./packages/meow-ui-vite && npm run build
      - run: npm publish ./packages/meow-ui-vite/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.MEOW_UI_NPM_TOKEN}}
